#!/usr/bin/env bash
# run_lightscan.sh — photostatistics scale ladder for RADiCALsimSIMPLE.
#
# THE QUESTION THIS ANSWERS. Every sigma_t we quote is measured at 1% light
# (RADSIMPLE_LIGHT_SCALE=1e-2), because tracking all ~5e8 optical photons per
# 120 GeV event is intractable. A single thinned run CANNOT tell you where the
# true-light resolution lands, because the measured width mixes two terms that
# behave completely differently as light increases:
#
#     sigma_t^2(f) = A^2 / f  +  B^2
#                    \____/     \__/
#                photon counting  light-INDEPENDENT floor
#                (shrinks as f)   (never shrinks: fibre transit-time
#                                  spread, path dispersion, geometry)
#
# Fitting that straight line (sigma_t^2 vs 1/f) over several light levels
# separates them, and B is the honest answer to "does <10 ps survive at true
# light?". Extrapolating a single point instead ASSUMES B=0 — the assumption
# that hid a 43.5 ps floor in the DSB sim's own ladder (see
# ../RADiCALsimLadder/README.md). This study is the SIMPLE-family equivalent.
#
# THIS IS A STUDY, NOT A DETECTOR. It reuses the RADiCALsimSIMPLE binary and
# geometry unchanged — the only thing that varies between rungs is the light
# scale. Nothing here forks the simulation.
#
#   cd RADiCALsimLightScan && bash run_lightscan.sh [NEVT]     (default 2000)
#
# On a cluster, under nohup — no redirect needed, it logs itself:
#   nohup bash run_lightscan.sh 2000 &
#   tail -f build/logs/run_lightscan.log
#
# Output: build/rootfiles/f<scale>/E<N>GeV.root, one subdir per rung.
# Analyze: root -l -b -q analysis/lightscan.C
set -eu

HERE="$(cd "$(dirname "$0")" && pwd)"

# --- standard logging: writes to <sim>/build/logs/<script>.log --------------
# Repo-wide convention, see simulations/README_LOGGING.md.
. "$HERE/../lib/run_logging.sh"
start_logging "$HERE"

SIMPLE="$HERE/../RADiCALsimSIMPLE"
BIN="$SIMPLE/build/radsimple"
NEVT="${1:-2000}"

# Rungs: 1e-2 is the standard production scale every existing result uses, so
# it anchors the ladder to numbers you already trust. Spanning 1e-3..3e-2 is a
# 30x lever in f, i.e. ~5.5x in sigma_t — plenty to resolve the A/B split.
# Cost scales ~linearly with f (more photons = more tracking), so the top rung
# dominates: keep the list short and let 3e-2 be the expensive one.
FACTORS="${RADSIMPLE_LIGHT_FACTORS:-1e-3 3e-3 1e-2 3e-2}"

# Two energies is enough to check the A/B split is not an artifact of one
# operating point, and costs far less than the full 6-energy grid.
ENERGIES="${RADSIMPLE_ENERGIES:-25 120}"

[ -x "$BIN" ] || {
    echo "ERROR: no RADiCALsimSIMPLE binary at $BIN"
    echo "Build it first:"
    echo "  cd $SIMPLE/build && source ../setup_env.sh && cmake .. -DCMAKE_PREFIX_PATH=\$CONDA_PREFIX && make -j"
    exit 1; }

ESUM=$(echo $ENERGIES | tr ' ' '\n' | awk '{s+=$1} END {print s}')
CORES="${RADSIMPLE_THREADS:-$( (nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 1) )}"
NF=$(echo $FACTORS | wc -w | tr -d ' ')

# ETA: 5.63 core-s/event/GeV measured at f=1e-2 on curiosity (2026-07-28 file
# timestamps). Runtime scales ~linearly with f, so weight each rung by f/1e-2.
FSUM=$(echo $FACTORS | tr ' ' '\n' | awk '{s+=$1/0.01} END {print s}')
ETA=$(awk -v n="$NEVT" -v es="$ESUM" -v k="$CORES" -v fs="$FSUM" \
      'BEGIN {printf "%.1f", 5.63*n*es*fs/k/3600}')

echo "=================================================================="
echo " RADiCALsimLightScan — photostatistics ladder"
echo "   binary    : RADiCALsimSIMPLE (reused, unmodified)"
echo "   rungs     : $FACTORS   ($NF light scales)"
echo "   energies  : $ENERGIES GeV"
echo "   events    : $NEVT per energy per rung"
echo "   cores     : $CORES"
echo "   rough ETA : ~${ETA} h  (top rung dominates — cost ~ f)"
echo "   output    : build/rootfiles/f<scale>/"
echo "=================================================================="

for f in $FACTORS; do
    d="$HERE/build/rootfiles/f$f"
    mkdir -p "$d"
    MACRO="$HERE/build/sweep_f$f.mac"
    {
        echo "# generated by run_lightscan.sh — rung f=$f — $(date)"
        echo "/run/initialize"
        echo "/run/printProgress $(( NEVT / 4 + 1 ))"
        for E in $ENERGIES; do
            echo ""
            echo "/analysis/setFileName $d/E${E}GeV"
            echo "/gun/energy $E GeV"
            echo "/run/beamOn $NEVT"
        done
    } > "$MACRO"

    echo ""
    echo "--- rung f=$f ---"
    start=$(date +%s)
    # RADSIMPLE_LIGHT_SCALE is COHERENT: it scales LYSO scintillation at the
    # source AND (via StackingAction) thins Cherenkov by the same factor, so
    # the light MIX stays physical at every rung and f is a pure intensity
    # lever. That is what makes the A/B fit meaningful.
    ( cd "$SIMPLE/build" && RADSIMPLE_LIGHT_SCALE="$f" ./radsimple "$MACRO" ) \
        || { echo "    FAILED at rung f=$f"; continue; }
    echo "    done in $(( $(date +%s) - start ))s  -> build/rootfiles/f$f/"
done

echo ""
echo "=================================================================="
echo " ladder complete. Analyze:"
echo "   root -l -b -q analysis/lightscan.C"
echo "=================================================================="
