#!/usr/bin/env bash
# run_simple.sh — launch the standard RADiCALsimSIMPLE sweep with standard logging.
#
#   bash run_simple.sh                  # run.mac (the 6-energy sweep)
#   bash run_simple.sh run_short.mac    # any other macro in this folder
#   bash run_simple.sh 5000                       # generate+run a 5k sweep
#   RADSIMPLE_OUT_SUBDIR=centerE RADSIMPLE_CENTER_ETYPE=1 \
#     bash run_simple.sh 5000                     # -> rootfiles/centerE/, the
#                                                  # canonical rootfiles/*.root
#                                                  # baseline is left untouched
#
# On a cluster, under nohup so it survives an SSH drop — no redirect needed:
#   nohup bash run_simple.sh &
#   tail -f build/logs/run_simple.log
#
# This is a THIN WRAPPER. It changes nothing about how the sim runs; it only
# puts the live Geant4 output in the repo-standard place
# (<sim>/build/logs/<script>.log — see simulations/README_LOGGING.md) so you
# never have to remember where you redirected it.
#
# Running `./radsimple run.mac` by hand from build/ still works exactly as
# before and is unaffected by this script.
set -eu

HERE="$(cd "$(dirname "$0")" && pwd)"

# --- standard logging: writes to <sim>/build/logs/<script>.log --------------
. "$HERE/../lib/run_logging.sh"
start_logging "$HERE"

BIN="$HERE/build/radsimple"
[ -x "$BIN" ] || { echo "ERROR: no binary at $BIN"; echo "Build it first: see README."; exit 1; }

ENERGIES="${RADSIMPLE_ENERGIES:-5 10 25 50 100 120}"
ESUM=$(echo $ENERGIES | tr ' ' '\n' | awk '{s+=$1} END {print s}')
CORES="${RADSIMPLE_THREADS:-$( (nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 1) )}"

# RADSIMPLE_OUT_SUBDIR: write to rootfiles/<subdir>/ instead of rootfiles/
# directly. Use this for any non-default-flag run (center E-type, a light
# scan rung, ...) so the canonical baseline in rootfiles/ — which other
# studies stage as their control (e.g. RADiCALsimWrap/stage_control.sh) —
# is never at risk of being silently overwritten.
SUBDIR="${RADSIMPLE_OUT_SUBDIR:-}"
OUTDIR="rootfiles${SUBDIR:+/$SUBDIR}"
mkdir -p "$HERE/build/$OUTDIR"

if [ $# -ge 1 ] && [ -z "${1//[0-9]/}" ]; then
    # -------- numeric argument: GENERATE the sweep macro at that event count --
    # Generating (rather than editing macros/run.mac) sidesteps this repo's
    # most-repeated failure mode: CMake copies macros/*.mac into build/ at
    # CONFIGURE time only, so editing a macro and re-running just `make` runs
    # the STALE copy. A generated macro cannot go stale.
    NEV="$1"
    MACRO="sweep_${NEV}ev${SUBDIR:+_$SUBDIR}.mac"
    {
        echo "# generated by run_simple.sh — $(date)"
        echo "/run/initialize"
        echo "/run/printProgress $(( NEV / 5 + 1 ))"
        for E in $ENERGIES; do
            echo ""
            echo "/analysis/setFileName $OUTDIR/E${E}GeV"
            echo "/gun/energy $E GeV"
            echo "/run/beamOn $NEV"
        done
    } > "$HERE/build/$MACRO"
    # ETA from MEASURED curiosity throughput (2026-07-28 file timestamps):
    # 55.0 s per GeV per 5000 events on 512 threads = 5.63 core-s/event/GeV,
    # linear in beam energy to <1%.
    ETA=$(awk -v n="$NEV" -v es="$ESUM" -v k="$CORES" \
          'BEGIN {printf "%.1f", 5.63*n*es/k/3600}')
else
    # -------- no argument (or a filename): use a macro from macros/ ----------
    MACRO="${1:-run.mac}"
    NEV="(set in $MACRO)"
    ETA="?"
    [ -f "$HERE/build/$MACRO" ] || { echo "ERROR: no $MACRO in $HERE/build/"; \
        echo "Macros live in macros/ and are copied to build/ by CMake."; \
        echo "If you just edited or added one, re-run 'cmake ..' from build/."; exit 1; }
fi

echo "=================================================================="
echo " RADiCALsimSIMPLE"
echo "   macro     : $MACRO"
echo "   energies  : $ENERGIES GeV"
echo "   events    : $NEV per energy"
echo "   cores     : $CORES"
echo "   rough ETA : ~${ETA} h"
echo "   output    : build/$OUTDIR/E<N>GeV.root"
echo "=================================================================="

start=$(date +%s)
cd "$HERE/build"
./radsimple "$MACRO"
echo "done in $(( $(date +%s) - start ))s  -> build/$OUTDIR/"
