#!/usr/bin/env bash
# run_wrap_scan.sh — run the Tyvek-wrapped module.
#
#   bash run_wrap_scan.sh          # 2500 events x the same 6 energies as SIMPLE
#   bash run_wrap_scan.sh 500      # quick look: 500 events per energy
#
# On a cluster, always under nohup so it survives an SSH drop:
#   nohup bash run_wrap_scan.sh > scan.log 2>&1 &
#
# ONE config: Tyvek (R=0.98 diffuse, 0.1 mm air gap — the same reflectivity the
# inter-layer foils already use) on the module's 4 exposed side faces.
#
# THE CONTROL IS NOT RUN HERE. RADiCALsimWrap with no RADWRAP_* flags builds
# geometry byte-identical to RADiCALsimSIMPLE, so the SIMPLE sweep you already
# have IS the no-wrap control. Stage it when you analyze:
#   bash stage_control.sh /path/to/RADiCALsimSIMPLE/build
#
# Output: results/tyvek/E<N>GeV.root, plus sweep.mac and run.log so every
# number is traceable to the exact macro and banner that produced it.
set -eu

# --- standard logging: writes to <sim>/build/logs/<script>.log --------------
# Repo-wide convention, see simulations/README_LOGGING.md. No redirect needed:
#   nohup bash THIS_SCRIPT.sh &     ->   tail -f build/logs/<script>.log
. "$(cd "$(dirname "$0")" && pwd)/../lib/run_logging.sh"
start_logging "$(cd "$(dirname "$0")" && pwd)"

HERE="$(cd "$(dirname "$0")" && pwd)"
BIN="$HERE/build/radwrap"
NEV="${1:-2500}"
# Same 6 energies as RADiCALsimSIMPLE's run.mac, so the comparison against the
# staged control is point-for-point.
ENERGIES="${RADWRAP_ENERGIES:-5 10 25 50 100 120}"

[ -x "$BIN" ] || { echo "ERROR: no binary at $BIN"; echo "Build it first — see README step 1."; exit 1; }

NE=$(echo $ENERGIES | wc -w | tr -d ' ')
ESUM=$(echo $ENERGIES | tr ' ' '\n' | awk '{s+=$1} END {print s}')

# ETA from a MEASURED calibration (2026-07-28, 1 core): ~1.24 core-s per event
# per GeV without the wrap, ~2.2x that with it. Scales ~linearly with energy
# and event count. (Cross-checked against SIMPLE's real 1 h / 5000x6 / 512-core
# curiosity run, so it transfers to cluster hardware.)
CORES="${RADSIMPLE_THREADS:-$( (nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 1) )}"
ETA=$(awk -v n="$NEV" -v es="$ESUM" -v k="$CORES" \
      'BEGIN {printf "%.1f", 1.24*n*es*2.2/k/3600}')

echo "=================================================================="
echo " Tyvek wrap run"
echo "   energies  : $ENERGIES GeV"
echo "   events    : $NEV per energy  ($((NE * NEV)) total)"
echo "   cores     : $CORES"
echo "   rough ETA : ~${ETA} h"
echo "=================================================================="

d="$HERE/results/tyvek"
mkdir -p "$d"

# The macro is GENERATED here, next to its own output — never copied by CMake.
# That removes RADiCALsimSIMPLE's most-repeated failure mode, where editing a
# .mac and running only `make` silently executes a stale copy.
{
    echo "# generated by run_wrap_scan.sh"
    echo "# $(date)"
    echo "/run/initialize"
    echo "/random/setSeeds 20260728 1"
    echo "/run/printProgress $((NEV / 4 + 1))"
    for E in $ENERGIES; do
        echo ""
        echo "/analysis/setFileName E${E}GeV"
        echo "/gun/energy $E GeV"
        echo "/run/beamOn $NEV"
    done
} > "$d/sweep.mac"

echo "--- tyvek  (sides, R=0.98 diffuse, 0.1 mm air gap) ---"
# Geant4's own output — the actual live progress — goes to the standard log
# location so it can be tailed without hunting through results/.
G4LOG="$HERE/build/logs/tyvek_geant4.log"
mkdir -p "$HERE/build/logs"
echo "    Geant4 progress -> build/logs/tyvek_geant4.log  (tail -f that one)"
start=$(date +%s)
(
    cd "$d"
    RADWRAP_SIDES=1 "$BIN" sweep.mac > "$G4LOG" 2>&1
)
echo "    done in $(( $(date +%s) - start ))s  -> results/tyvek/"
# Keep a copy next to the data so the result folder stays self-documenting.
cp "$G4LOG" "$d/run.log"
grep -h "outer wrap" "$G4LOG" | head -1 | sed 's/^/    /' || true

echo "=================================================================="
echo " done. Next (on the Mac):"
echo "   bash pull_wrap_results.sh perseverence"
echo "   bash stage_control.sh ../RADiCALsimSIMPLE/build"
echo "   root -l -b -q analysis/wrap_scan.C"
echo "=================================================================="
