#!/usr/bin/env bash
# run_wrap_scan.sh — the whole study in one command.
#
# Runs the SAME energy sweep once per wrap configuration and drops each one in
# its own folder, so `analysis/wrap_scan.C` can compare them against the
# no-wrap control.
#
# NO "none" CONFIG IS RUN BY DEFAULT. RADiCALsimSIMPLE's own sweep (run.mac,
# no wrap flags — they don't exist there) IS this study's control already,
# byte-identical geometry. Stage an already-completed SIMPLE run as "none"
# instead of burning compute re-running it:
#   bash stage_control.sh /path/to/RADiCALsimSIMPLE/build
# (see that script's header for the exact same-seed caveat). Only pass
# RADWRAP_CONFIGS="none ..." below if you specifically want a fresh,
# same-random-seed control run through THIS binary instead.
#
# Defaults match run.mac (RADiCALsimSIMPLE's standard sweep) exactly — 5000
# events at the same 6 energies — so a staged control lines up point-for-point:
#   bash run_wrap_scan.sh                 # defaults: 5000 events, 5/10/25/50/100/120 GeV
#   bash run_wrap_scan.sh 1000            # quicker: 1000 events per energy
#   RADWRAP_CONFIGS="tyvek esr" bash run_wrap_scan.sh        # just two configs
#   RADWRAP_ENERGIES="50" bash run_wrap_scan.sh 5000         # one energy, deep
#
# On a cluster, run the whole thing under nohup:
#   nohup bash run_wrap_scan.sh > scan.log 2>&1 &
#
# Output: results/<config>/E<N>GeV.root  (+ sweep.mac and run.log per config,
# so every number is traceable to the exact macro and banner that produced it).
set -eu

HERE="$(cd "$(dirname "$0")" && pwd)"
BIN="$HERE/build/radwrap"
NEV="${1:-5000}"
ENERGIES="${RADWRAP_ENERGIES:-5 10 25 50 100 120}"

# Each config is  name:sides:ends:reflectivity:finish:gap_mm
#
# REFLECTIVITY SOURCES — be honest about which of these are real numbers:
#   tyvek  0.98  : the value already used for the inter-layer foils in this
#                  project (standard detector-wrap spec, matches SIMPLE/DSB).
#   esr    0.985 : 3M ESR / VM2000 specular film, manufacturer spec.
#   mylar  0.90  : aluminized mylar, typical vendor spec for visible light.
#   delrin 0.60  : ESTIMATE, not a measurement. Stands in for the milled Delrin
#                  housing the real module actually sits in (2303.05580 sec II).
#                  Treat it as "some diffuse reflection happens", not a number
#                  to quote.
#   black  0.02  : absorbing wrap — the pessimistic bound.
ALL_CONFIGS=(
  "none:0:0:0.98:diffuse:0.1"            # CONTROL — identical to RADiCALsimSIMPLE
  "tyvek:1:0:0.98:diffuse:0.1"           # the actual proposal: Tyvek on the 4 long faces
  "tyvek_ends:1:1:0.98:diffuse:0.1"      # same + end caps (all 6 faces)
  "esr:1:0:0.985:specular:0.1"           # 3M ESR / VM2000 specular film
  "mylar:1:0:0.90:specular:0.1"          # aluminized mylar
  "delrin:1:0:0.60:diffuse:0.1"          # the Delrin housing that is already there
  "tyvek_contact:1:0:0.98:diffuse:0.0"   # gap=0: kills LYSO/air TIR (the trap)
  "black:1:0:0.02:diffuse:0.1"           # absorbing wrap — pessimistic bound
)

# Optional subset: RADWRAP_CONFIGS="none tyvek esr"
if [ -n "${RADWRAP_CONFIGS:-}" ]; then
    SELECTED=()
    for want in $RADWRAP_CONFIGS; do
        found=""
        for cfg in "${ALL_CONFIGS[@]}"; do
            [ "${cfg%%:*}" = "$want" ] && { SELECTED+=("$cfg"); found=1; break; }
        done
        [ -n "$found" ] || { echo "unknown config '$want'"; exit 1; }
    done
    CONFIGS=("${SELECTED[@]}")
else
    # Default: every config EXCEPT "none" — see the header comment. It stays
    # in ALL_CONFIGS so `RADWRAP_CONFIGS="none ..."` can still ask for a fresh,
    # same-seed control run through this binary when that is actually wanted.
    CONFIGS=()
    for cfg in "${ALL_CONFIGS[@]}"; do
        [ "${cfg%%:*}" = "none" ] || CONFIGS+=("$cfg")
    done
    echo "(skipping 'none' by default — stage an existing SIMPLE run instead:"
    echo " bash stage_control.sh /path/to/RADiCALsimSIMPLE/build)"
fi

[ -x "$BIN" ] || { echo "no binary at $BIN — build first (see README step 1)"; exit 1; }

NE=$(echo $ENERGIES | wc -w | tr -d ' ')
echo "=========================================================="
echo " wrap scan: ${#CONFIGS[@]} configs x $NE energies x $NEV events"
echo " energies : $ENERGIES GeV"
echo " threads  : ${RADSIMPLE_THREADS:-all cores}"
echo " total    : $(( ${#CONFIGS[@]} * NE * NEV )) events"
echo "=========================================================="

for cfg in "${CONFIGS[@]}"; do
    IFS=: read -r name sides ends refl finish gap <<< "$cfg"
    d="$HERE/results/$name"
    mkdir -p "$d"

    # Generate the sweep macro next to its own output. Generated, not copied by
    # CMake, so it can never go stale relative to what you asked for — and it is
    # kept afterwards as a record of exactly what ran.
    {
        echo "# generated by run_wrap_scan.sh for config '$name'"
        echo "/run/initialize"
        echo "/random/setSeeds 20260728 1"   # same seeds every config -> the
                                             # shower fluctuations are common
                                             # mode, so config differences are
                                             # not buried in beam statistics
        echo "/run/printProgress $(( NEV / 4 + 1 ))"
        for E in $ENERGIES; do
            echo ""
            echo "/analysis/setFileName E${E}GeV"
            echo "/gun/energy $E GeV"
            echo "/run/beamOn $NEV"
        done
    } > "$d/sweep.mac"

    echo ""
    echo "--- $name  (sides=$sides ends=$ends R=$refl $finish gap=${gap}mm) ---"
    start=$(date +%s)
    (
        cd "$d"
        RADWRAP_SIDES="$sides" RADWRAP_ENDS="$ends" \
        RADWRAP_REFLECTIVITY="$refl" RADWRAP_FINISH="$finish" \
        RADWRAP_GAP_MM="$gap" \
        "$BIN" sweep.mac > run.log 2>&1
    )
    echo "    done in $(( $(date +%s) - start ))s -> results/$name/"
    grep -h "^\[WRAP\] outer wrap" "$d/run.log" | head -1 | sed 's/^/    /'
done

echo ""
echo "=========================================================="
echo " all configs done. Analyze with:"
echo "   root -l -b -q analysis/wrap_scan.C"
echo "=========================================================="
