#!/usr/bin/env bash
# run_tb26.sh — run one capillary configuration of the August 2026 T10 beam test
# at the energies that were actually taken (from the run manifest spreadsheet).
#
#   bash run_tb26.sh LUAG            # LuAG:Ce filaments, 1 3 5 7 9 11 GeV, 2000 events each
#   bash run_tb26.sh DSB1            # DSB1 filaments,    1 3 5 7 9 11 GeV
#   bash run_tb26.sh DSB1 500        # any event count
#   nohup bash run_tb26.sh LUAG &    # on the cluster — survives an SSH drop, logs itself
#   tail -f build/logs/run_tb26.log
#
# Output: build/rootfiles/<material>/E<N>GeV.root   (one file per energy)
# Analyze: root -l -b -q analysis/tb26.C
#
# Knobs (environment variables, all optional):
#   RADSIMPLE_LIGHT_SCALE   light fraction f. DEFAULT 1.0 = TRUE LIGHT, no thinning,
#                           no extrapolation — affordable at 1-11 GeV on the cluster.
#                           Use 1e-2 for a quick local check.
#   RADSIMPLE_ENERGIES      override the energy list, e.g. "5 11"
#   RADSIMPLE_OUT_SUBDIR    override the output folder name (default: material, lowercase)
#   RADSIMPLE_THREADS       worker threads (default: all cores)
set -eu

HERE="$(cd "$(dirname "$0")" && pwd)"
. "$HERE/../lib/run_logging.sh"
start_logging "$HERE"

MAT="${1:-}"
NEV="${2:-2000}"
MATU=$(echo "$MAT" | tr '[:lower:]' '[:upper:]' | tr -d ':')
[ "$MATU" = "LUAGCE" ] && MATU="LUAG"

case "$MATU" in
    LUAG)  DEFAULT_E="1 3 5 7 9 11" ;;   # manifest: configuration A, runs 12-30
    DSB1)  DEFAULT_E="1 3 5 7 9 11" ;;   # manifest: configuration B, runs 31-38
    EJ199) echo "ERROR: EJ199 (configuration C, runs 39-43, 1 3 5 7 9 GeV) is not simulated yet:"
           echo "       its wavelength-shifter properties are unknown. Add them to"
           echo "       src/DetectorConstruction.cc DefineMaterials() first."; exit 1 ;;
    *)     echo "usage: bash run_tb26.sh <LUAG|DSB1> [events-per-energy]"; exit 1 ;;
esac

BIN="$HERE/build/radtb26"
[ -x "$BIN" ] || { echo "ERROR: no binary at $BIN — build first (see README)."; exit 1; }

ENERGIES="${RADSIMPLE_ENERGIES:-$DEFAULT_E}"
F="${RADSIMPLE_LIGHT_SCALE:-1.0}"
SUBDIR="${RADSIMPLE_OUT_SUBDIR:-$(echo "$MATU" | tr '[:upper:]' '[:lower:]')}"
CORES="${RADSIMPLE_THREADS:-$( (nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 1) )}"
ESUM=$(echo $ENERGIES | tr ' ' '\n' | awk '{s+=$1} END {print s}')

# Cost model, measured on this project's runs:
#   core-seconds per event per GeV at f = 1e-2:  5.63 (curiosity), 1.5 (the Mac)
#   scales linearly with f. Disk: ~0.052 MB per event per GeV per unit f (the
#   stored waveform), measured from the 120 GeV f=0.5 run (3.1 MB/event).
if [ "$CORES" -ge 64 ]; then K=5.63; HOST=cluster; else K=1.5; HOST=Mac; fi
ETA=$(awk -v n="$NEV" -v es="$ESUM" -v k="$CORES" -v f="$F" -v c="$K" \
      'BEGIN {printf "%.1f", c*(f/0.01)*n*es/k/3600}')
DISK=$(awk -v n="$NEV" -v es="$ESUM" -v f="$F" 'BEGIN {printf "%.1f", 0.052*f*es*n/1024}')

mkdir -p "$HERE/build/rootfiles/$SUBDIR"
MACRO="$HERE/build/sweep_${SUBDIR}_${NEV}ev.mac"
{
    echo "# generated by run_tb26.sh — $(date) — material $MATU, f=$F"
    echo "/run/initialize"
    echo "/run/printProgress $(( NEV / 5 + 1 ))"
    for E in $ENERGIES; do
        echo ""
        echo "/analysis/setFileName rootfiles/$SUBDIR/E${E}GeV"
        echo "/gun/energy $E GeV"
        echo "/run/beamOn $NEV"
    done
} > "$MACRO"

echo "=================================================================="
echo " Aug26TestBeam — CERN T10, upstream-only readout"
echo "   filament   : $MATU"
echo "   energies   : $ENERGIES GeV   ($NEV events each)"
echo "   light      : f = $F $( [ "$F" = "1.0" ] || [ "$F" = "1" ] && echo '(TRUE light)' )"
echo "   cores      : $CORES ($HOST)"
echo "   rough ETA  : ~${ETA} h      rough disk: ~${DISK} GB"
echo "   output     : build/rootfiles/$SUBDIR/E<N>GeV.root"
echo "   macro      : $MACRO"
echo "=================================================================="

start=$(date +%s)
( cd "$HERE/build" && RADSIMPLE_CAPILLARY="$MATU" RADSIMPLE_LIGHT_SCALE="$F" ./radtb26 "$MACRO" )
echo ""
echo "done in $(( $(date +%s) - start ))s  -> build/rootfiles/$SUBDIR/"
echo "next: root -l -b -q analysis/tb26.C"
